// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Problem struct {
	ID            int     `json:"id"`
	Title         string  `json:"title"`
	Description   string  `json:"description"`
	AcceptedRatio float64 `json:"accepted_ratio"`
	Tags          []*Tag  `json:"tags"`
	Authors       []*User `json:"authors"`
}

type Submission struct {
	ID             int      `json:"id"`
	Problem        *Problem `json:"problem"`
	CreatedAt      string   `json:"created_at"`
	Status         string   `json:"status"`
	CheckerMessage *string  `json:"checker_message"`
}

type Tag struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	HexColor string `json:"hex_color"`
}

type User struct {
	ID       int     `json:"id"`
	Username string  `json:"username"`
	FullName *string `json:"full_name"`
}
